---
- hosts: "{{ user }}" 
  vars:
    home: "/home/{{ user }}"
    nvim_location: "/home/{{ user }}/.local/applications/neovim"

  roles:
    - create_directories
    - install_packages
    - install_fonts
    - configure_terminal

  tasks:

    - name: Pull dotfiles into bare repo
      git:
        repo: "git@github.com:brahste/dotfiles.git"
        dest: "{{ home }}/.cfg"
        bare: yes

    - name: Backup conflicting dotfiles
      file: 
        path: "{{ home }}/.config-backup"
        state: directory

    - name: Delete Terminator config 
      file: 
        path: "{{ home }}/.config/terminator/config"
        state: absent 

    - name: Delete Terminator config 
      file: 
        path: "{{ home }}/.zshrc"
        state: absent 

    - name: Install Rustup
      shell:
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
