---
- name: Install core packages
  become: true
  apt:
    pkg:
      - build-essential
      - terminator
      - zsh
      - git
      - libfuse2
      - curl

- name: Install utility applications 
  become: true
  apt:
    pkg:
      - wireshark

- name: Download ripgrep
  vars: 
    item: ripgrep 
  get_url:
    url="https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb"
    dest="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"
- name: Install ripgrep
  become: true
  vars: 
    item: ripgrep 
  apt: deb="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"
  sudo: true

- name: Download batcat 
  vars: 
    item: batcat
  get_url:
    url="https://github.com/sharkdp/bat/releases/download/v0.21.0/bat-musl_0.21.0_amd64.deb"
    dest="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"
- name: Install batcat 
  become: true
  vars: 
    item: batcat
  apt: deb="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"

- name: Download fd-find 
  vars: 
    item: fdfind 
  get_url:
    url="https://github.com/sharkdp/fd/releases/download/v8.4.0/fd_8.4.0_amd64.deb"
    dest="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"
- name: Install fd-find 
  become: true
  vars: 
    item: fdfind 
  apt: deb="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"

- name: Download lsd 
  vars: 
    item: lsd 
  get_url:
    url="https://github.com/Peltoche/lsd/releases/download/0.22.0/lsd_0.22.0_amd64.deb"
    dest="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"
- name: Install lsd 
  become: true
  vars: 
    item: lsd 
  apt: deb="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"

- name: Download vivid 
  vars: 
    item: vivid 
  get_url:
    url="https://github.com/sharkdp/vivid/releases/download/v0.8.0/vivid_0.8.0_amd64.deb"
    dest="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"
- name: Install vivid 
  become: true
  vars: 
    item: vivid 
  apt: deb="/home/{{ ansible_user_id }}/Downloads/{{ item }}.deb"

